function dstates = ballandbeamDynSys(M,m,Ja,L,g,r,rdot,alpha,alphadot,taualpha,fr)
%BALLANDBEAMDYNSYS
%    DSTATES = BALLANDBEAMDYNSYS(M,M,JA,L,G,R,RDOT,ALPHA,ALPHADOT,TAUALPHA,FR)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    23-Apr-2017 21:35:47

dstates = [alphadot;rdot;(taualpha-alphadot.*m.*r.*rdot.*2.0)./(Ja+m.*r.^2);fr.*(5.0./7.0)+g.*7.130958331916297e-2+alphadot.*r.*(5.0./7.0)];
