function [Ac,Bc,Gc] = furutaDynMat(alpha,beta,gamma,delta,theta,thetadot,phi,phidot,tauphi,tautheta)
%FURUTADYNMAT
%    [AC,BC,GC] = FURUTADYNMAT(ALPHA,BETA,GAMMA,DELTA,THETA,THETADOT,PHI,PHIDOT,TAUPHI,TAUTHETA)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    23-Apr-2017 20:37:15

t2 = cos(theta);
t3 = sin(theta);
t4 = beta.^2;
t5 = alpha.*beta;
t6 = gamma.^2;
t7 = t2.^2;
t8 = t3.^2;
t9 = t4.*t8;
t12 = t6.*t7;
t10 = t5+t9-t12;
t11 = 1.0./t10;
Ac = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,-t2.*t11.*(t3.*t4.*thetadot+beta.*gamma.*phidot.*t2.*t3),t11.*(alpha.*beta.*phidot.*t2.*t3+beta.*gamma.*t3.*t7.*thetadot+phidot.*t2.*t3.*t4.*t8),0.0,1.0,t11.*(beta.*gamma.*t3.*thetadot-phidot.*t2.*t3.*t4),-t11.*(t2.*t3.*t6.*thetadot-beta.*gamma.*phidot.*t3.*t7)],[4,4]);
if nargout > 1
    Bc = reshape([0.0,0.0,beta.*t11,-gamma.*t2.*t11,0.0,0.0,-gamma.*t2.*t11,t11.*(alpha+beta.*t8)],[4,2]);
end
if nargout > 2
    Gc = [0.0;0.0;0.0;-delta.*t3];
end
