function dstates = furutaDynSys(alpha,beta,gamma,delta,theta,thetadot,phi,phidot,tauphi,tautheta)
%FURUTADYNSYS
%    DSTATES = FURUTADYNSYS(ALPHA,BETA,GAMMA,DELTA,THETA,THETADOT,PHI,PHIDOT,TAUPHI,TAUTHETA)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    23-Apr-2017 20:37:15

t2 = cos(theta);
t3 = sin(theta);
t4 = t2.^2;
t5 = beta.^2;
t6 = alpha.*beta;
t7 = gamma.^2;
t8 = t3.^2;
t9 = t5.*t8;
t10 = t6+t9-t4.*t7;
t11 = 1.0./t10;
t12 = phidot.^2;
t13 = thetadot.^2;
dstates = [phidot;thetadot;-t11.*(-beta.*tauphi+gamma.*t2.*tautheta-beta.*gamma.*t3.*t13+delta.*gamma.*t2.*t3+beta.*gamma.*t3.*t4.*t12+phidot.*t2.*t3.*t5.*thetadot.*2.0);t11.*(alpha.*tautheta+alpha.*delta.*t3+beta.*t8.*tautheta-gamma.*t2.*tauphi+beta.*delta.*t3.*t8-t2.*t3.*t7.*t13+alpha.*beta.*t2.*t3.*t12+t2.*t3.*t5.*t8.*t12+beta.*gamma.*phidot.*t3.*t4.*thetadot.*2.0)];
