function [Amat,Bmat] = ballandbeamLinSys(M,m,Ja,L,g,r,rdot,alpha,alphadot,taualpha,fr)
%BALLANDBEAMLINSYS
%    [AMAT,BMAT] = BALLANDBEAMLINSYS(M,M,JA,L,G,R,RDOT,ALPHA,ALPHADOT,TAUALPHA,FR)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    23-Apr-2017 21:35:48

t2 = r.^2;
t3 = m.*t2;
t4 = Ja+t3;
t5 = 1.0./t4;
Amat = reshape([0.0,0.0,0.0,0.0,0.0,0.0,alphadot.*m.*rdot.*t5.*-2.0-m.*r.*1.0./t4.^2.*(taualpha-alphadot.*m.*r.*rdot.*2.0).*2.0,alphadot.*(5.0./7.0),1.0,0.0,m.*r.*rdot.*t5.*-2.0,r.*(5.0./7.0),0.0,1.0,alphadot.*m.*r.*t5.*-2.0,0.0],[4,4]);
if nargout > 1
    Bmat = reshape([0.0,0.0,t5,0.0,0.0,0.0,0.0,5.0./7.0],[4,2]);
end
