function [Amat,Bmat] = furutaLinSys(alpha,beta,gamma,delta,theta,thetadot,phi,phidot,tauphi,tautheta)
%FURUTALINSYS
%    [AMAT,BMAT] = FURUTALINSYS(ALPHA,BETA,GAMMA,DELTA,THETA,THETADOT,PHI,PHIDOT,TAUPHI,TAUTHETA)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    23-Apr-2017 20:37:16

t2 = cos(theta);
t3 = sin(theta);
t4 = t2.^2;
t5 = t3.^2;
t6 = beta.^2;
t7 = phidot.^2;
t8 = gamma.^2;
t9 = alpha.*beta;
t10 = t5.*t6;
t13 = t4.*t8;
t11 = t9+t10-t13;
t12 = thetadot.^2;
t14 = 1.0./t11;
t15 = t2.*t3.*t6.*2.0;
t16 = t2.*t3.*t8.*2.0;
t17 = t15+t16;
t18 = 1.0./t11.^2;
t19 = beta.*gamma.*phidot.*t3.*t4.*2.0;
Amat = reshape([0.0,0.0,0.0,0.0,0.0,0.0,t14.*(-delta.*gamma.*t4+delta.*gamma.*t5+gamma.*t3.*tautheta+beta.*gamma.*t2.*t12-phidot.*t4.*t6.*thetadot.*2.0+phidot.*t5.*t6.*thetadot.*2.0-beta.*gamma.*t2.*t4.*t7+beta.*gamma.*t2.*t5.*t7.*2.0)+t17.*t18.*(-beta.*tauphi+gamma.*t2.*tautheta-beta.*gamma.*t3.*t12+delta.*gamma.*t2.*t3+beta.*gamma.*t3.*t4.*t7+phidot.*t2.*t3.*t6.*thetadot.*2.0),t14.*(-t5.^2.*t6.*t7+alpha.*delta.*t2+gamma.*t3.*tauphi-t4.*t8.*t12+t5.*t8.*t12+alpha.*beta.*t4.*t7-alpha.*beta.*t5.*t7+beta.*delta.*t2.*t5.*3.0+beta.*t2.*t3.*tautheta.*2.0+t4.*t5.*t6.*t7.*3.0+beta.*gamma.*phidot.*t2.*t4.*thetadot.*2.0-beta.*gamma.*phidot.*t2.*t5.*thetadot.*4.0)-t17.*t18.*(alpha.*tautheta+alpha.*delta.*t3+beta.*t5.*tautheta-gamma.*t2.*tauphi+beta.*delta.*t3.*t5-t2.*t3.*t8.*t12+alpha.*beta.*t2.*t3.*t7+t2.*t3.*t5.*t6.*t7+beta.*gamma.*phidot.*t3.*t4.*thetadot.*2.0),1.0,0.0,-t14.*(t19+t2.*t3.*t6.*thetadot.*2.0),t14.*(alpha.*beta.*phidot.*t2.*t3.*2.0+beta.*gamma.*t3.*t4.*thetadot.*2.0+phidot.*t2.*t3.*t5.*t6.*2.0),0.0,1.0,t14.*(beta.*gamma.*t3.*thetadot.*2.0-phidot.*t2.*t3.*t6.*2.0),t14.*(t19-t2.*t3.*t8.*thetadot.*2.0)],[4,4]);
if nargout > 1
    Bmat = reshape([0.0,0.0,beta.*t14,-gamma.*t2.*t14,0.0,0.0,-gamma.*t2.*t14,t14.*(alpha+beta.*t5)],[4,2]);
end
